### ISSUE TITLE
[Docs] Github 협업 프로세스 정리

### ISSUE THREAD

**Issue by kssumin** [Step3-kakao-tech-campus/Team11_BE#4]
### 1.  개발 프로세스

---

1. issue 생성
2. issue 기반 branch 생성
    * `주의할 점!!!! weekly branch에서 새로운 branch를 생성해야 합니다!!!!!!`
4. issue와 관련된 feature 개발 완료
5. PR 혹은 merge commit 생성시에도 커밋 메세지 규칙에 맞춰 작성
6. PR이 주요 branch로 merge되기 위한 조건
    - 최소 1명의 review의 approve
    - CI로 인한 build success
    - test case 작성 (- optional)
7. merge 후 feature branch 제거
8. issue close

### 2. 커밋 규칙

---

> 다음은 커밋메세지의 형식입니다.
> 

```
  CommitType :: (#issue number) Subject
```

- Commit Type

> 다음은 커밋타입 형식입니다.
> 
    - `feat` : 새로운 기능 추가
    - `fix` : 버그 수정
    - `docs`: 문서관련
    - `style` : 스타일 변경 (포매팅 수정, 들여쓰기 추가, …)
    - `refactor` : 코드 리팩터링
    - `test` : 빠진 테스트 관련 코드
    - `chore` : 자잘한 수정

* issue number 

위에 #issue number 이라고 기재한 부분:
`#`뒤에 개발한 브런치가 기반을둔 issue number을 기입한다.

* Subject 

> 커밋메세지 형식의 Subject 부분에 기재
> 

50자를 넘기지 않게 명령형으로 작성한다.
한국어로 작성한다.
`어떻게` 보단 `무엇을`, `왜` 에 초점을 두고 작성한다.

```bash

"~수정 했다" → "~수정"

"Add~" → "~추가"
```

- Example

```
fix : 피드 버그 로직 수정
docs : README 파일 수정
```

### 3. 브랜치 규칙

---

- Feature Branch

```markdown
feature/{issue number}/{todo}
```

### 4. merge 전략

---

default는 squash merge이다.

### 5. 주의할 점

---

commit의 단위는 최대한 작게한다.

- Example

```
feat : 로그인 성공 테스트 코드 작성 및 회원가입 기능 구현 (x)
test : 로그인 성공 테스트 코드 작성 (0)
feat : 이메일 중복확인 구현(0)
```

리뷰하는 사람도 커밋메시지만 보고 어떤 코드인지 쉽게 파악할 수 있도록 커밋 메시지를 명확히 하자.

또한 PR 단위도 너무나도 크면 리뷰하는 사람의 입장에서도 부담스럽다.

따라서 PR 단위도 크게 하지 말자.

**Comment by jinwooseok** [comment]
OK
